all:
	gcc 2-1.c -o 2-1 -O3 -Wall
	gcc 2-2.c -o 2-2 -O3 -Wall
	gcc 2-3.c -o 2-3 -O3 -Wall
	gcc 2-4.c -o 2-4 -O3 -Wall

1:
	gcc 2-1.c -o 2-1 -O3 -Wall

2:
	gcc 2-2.c -o 2-2 -O3 -Wall

3:
	gcc 2-3.c -o 2-3 -O3 -Wall

4:
	gcc 2-4.c -o 2-4 -O3 -Wall

clean:
	rm -rf 2-1 2-2 2-3 2-4
