#!/bin/bash
# set up a file called correct output
echo "12" > correct_output
echo "0" >> correct_output
echo "246" >> correct_output
echo "1357" >> correct_output
echo "-776900" >> correct_output

gcc -o proj2c proj2c.c
./proj2c 4 + 8 > your_output
./proj2c 123 - 123 >> your_output
./proj2c 123 + 123 >> your_output
./proj2c 123 + 1234 >> your_output
./proj2c 12334 - 789234 >> your_output

diff correct_output your_output
if [[ $? == 0 ]] ; then
   echo "No difference!  You have it right"
else
   echo "Differences!  You have it wrong"
fi

