all:
	gcc 1-1.c -o 1-1 -O3 -Wall
	gcc 1-2.c -o 1-2 -O3 -Wall
	gcc 1-3.c -o 1-3 -O3 -Wall
	gcc 1-4.c -o 1-4 -O3 -Wall

1:
	gcc 1-1.c -o 1-1 -O3 -Wall

2:
	gcc 1-2.c -o 1-2 -O3 -Wall

3:
	gcc 1-3.c -o 1-3 -O3 -Wall

4:
	gcc 1-4.c -o 1-4 -O3 -Wall

clean:
	rm 1-1 1-2 1-3 1-4
