#!/bin/bash


if [[ ! -f 2H_correct_output ]] ; then
   echo "Error: you need to download the file 2H_correct_output and place it in this directory."
   echo "Exiting."
   exit 1
fi

#Check that code compiles with provided Makefile
gcc -o proj2H proj2H.c
if [[ $? != 0 ]] ; then
   echo "Compile failure!"
   exit 1
fi

./proj2H > your_output

#Check for correct output
diff 2H_correct_output your_output
if [[ $? != 0 ]] ; then
   echo "Your output is not correct."
   exit 1
fi

echo "Your program appears to be working correctly."
echo "It compiles, runs, and generates the correct output."
echo "Please upload your code to Canvas, following the instructions in the prompt."
echo "Grading will consist of the steps performed by this script, complemented by inspection of your code."

